
#
# docker compose file for testing
#

version: '3'
services:
  postgrestest:
    image: postgres:latest
    ports:
      - 5555:5432 # don't conflict with local posgresql
    container_name: service_postgrestest_1
