apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotations-service-deployment
  labels:
    app: annotations-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annotations-service
  template:
    metadata:
      labels:
        app: annotations-service
    spec:
      containers:
      - name: annotations-service
        image: gcr.io/devenv-215523/annotations-service:${SERVICE_VERSION}
        env:
          - name: POSTGRES_SCHEMA
            value: "${DB_SCHEMA}"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: annotations-db-credentials
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: annotations-db-credentials
                key: password
          - name: POSTGRES_DB
            value: "annotations-db"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=devenv-215523:us-east1:annotations-instance=tcp:5432",
                  "-credential_file=/secrets/cloudsql/staging-service-account.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: service-account-key
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key
---
apiVersion: v1
kind: Service
metadata:
  name: annotations-service-service
  labels:
    app: annotations-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: annotations-service
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: staging-annotations-tls
  namespace: default
spec:
  secretName: annotations-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: annotations.staging.wenglab.org
  dnsNames:
  - annotations.staging.wenglab.org
  acme:
    config:
    - http01:
        ingress: annotations-ingress
      domains:
      - annotations.staging.wenglab.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: annotations-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "staging-annotations-external-ip"
spec:
  backend:
    serviceName: annotations-service-service
    servicePort: 80
  tls:
  - secretName: annotations-tls
    hosts:
    - annotations.staging.wenglab.org
