#!/bin/bash
GCR_PROJECT_ID=devenv-215523
SERVICE_DOCKER_IMAGE_NAME=annotations-service
IMPORTER_DOCKER_IMAGE_NAME=annotations-importer
KUBE_DEPLOYMENT_NAME=annotations-service-deployment
KUBE_DEPLOYMENT_CONTAINER_NAME=annotations-service
