CREATE INDEX gene_quantification_$ASSEMBLY_experiment_accession ON gene_quantification_$ASSEMBLY(experiment_accession);
CREATE INDEX gene_quantification_$ASSEMBLY_file_accession ON gene_quantification_$ASSEMBLY(file_accession);
CREATE INDEX gene_quantification_$ASSEMBLY_gene_id ON gene_quantification_$ASSEMBLY(gene_id);
CREATE INDEX gene_quantification_$ASSEMBLY_tpm ON gene_quantification_$ASSEMBLY(tpm);
CREATE INDEX gene_quantification_$ASSEMBLY_fpkm ON gene_quantification_$ASSEMBLY(fpkm);

CREATE INDEX transcript_quantification_$ASSEMBLY_experiment_accession ON transcript_quantification_$ASSEMBLY(experiment_accession);
CREATE INDEX transcript_quantification_$ASSEMBLY_file_accession ON transcript_quantification_$ASSEMBLY(file_accession);
CREATE INDEX transcript_quantification_$ASSEMBLY_gene_id ON transcript_quantification_$ASSEMBLY(gene_id);
CREATE INDEX transcript_quantification_$ASSEMBLY_transcript_id ON transcript_quantification_$ASSEMBLY(transcript_id);
CREATE INDEX transcript_quantification_$ASSEMBLY_tpm ON transcript_quantification_$ASSEMBLY(tpm);
CREATE INDEX transcript_quantification_$ASSEMBLY_fpkm ON transcript_quantification_$ASSEMBLY(fpkm);